export const codeLines = [
    "",
    "const connectionRequest = await",
    'composio.toolkits.authorize(userId, "github");',
    "",
    "const redirectUrl =",
    "connectionRequest.redirectUrl;",
    "",
    "const connectedAccount = await",
    "connectionRequest.waitForConnection();",
    "",
    "const tools = await composio.tools.get(userId, {",
    '  toolkits: ["github"],',
    "});",
    "",
    "const response = await openai.chat.completions.create(",
    "{",
    '  model: "gpt-4o-mini",',
    '  messages: [{ role: "user", content: "Star the',
    '    composio repository on GitHub" }],',
    "  tools: tools,",
    '  tool_choice: "auto",',
    "});",
];
